version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
    - "3000:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./app:/var/www/html
  php:
    volumes:
    - ./app:/var/www/html
    image: php:8.3-fpm
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
    - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    env_file:
      - .env
volumes:
  mysql-data: 
